<a href="https://colab.research.google.com/github/fornieligulo/Analisis_Data_Twitter_BrigadirJ/blob/main/FINAL_SKRIPSI_003_CRAWLING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***CRAWLING DATA TWITTER***

In [1]:
# Install Library tweet
!pip install tweepy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: tweepy in /usr/local/lib/python3.10/dist-packages (4.13.0)
Requirement already satisfied: oauthlib<4,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from tweepy) (3.2.2)
Requirement already satisfied: requests<3,>=2.27.0 in /usr/local/lib/python3.10/dist-packages (from tweepy) (2.27.1)
Requirement already satisfied: requests-oauthlib<2,>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from tweepy) (1.3.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27.0->tweepy) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27.0->tweepy) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27.0->tweepy) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.27.0->tweepy) (3.4)

In [2]:
# Import Library
import tweepy
import pandas as pd
import numpy as np

# Isi API Key Twitter
API_key = 'x9KXRVQGAeuxPUjGZ3engtfBb'
API_secret = 'RTwnJjjWfLCwtQcktmNuw1Q1HyHzC68Z5N0mKEKSN1Qgo5mzOF'
access_token = '1430515782245490690-lBcjpRbtPVheumbzSuxjVclmQaNMjp'
access_token_secret = 'iaDTgheJbvhZQXApvIih7BGSY9bhASqlNNtP0Yn7EeYts'

# Autentikkasi API Key Twitter
auth = tweepy.OAuthHandler(API_key, API_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth)

# Menemukan tweet berdasarkan (Kata Kunci, Jumlah, Bahasa) 
tweets = api.search_tweets('sambo', count=200, lang='id')

# Tampilkan Tweets
tweets

# Cetak tweet yang dikumpulkan
data = pd.DataFrame()
data['Created At'] = [tweet.created_at for tweet in tweets]
data['Screen Name'] = [tweet.user.screen_name for tweet in tweets]
data['tweets'] = [tweet.text for tweet in tweets]
data['Location'] = [tweet.user.location for tweet in tweets]
data['Number of Retweet'] = [tweet.retweet_count for tweet in tweets]
data['Number of Like'] = [tweet.favorite_count for tweet in tweets]
display(data.head(20))

# Save as .CSV
data.to_csv('dataSambo.csv')

,Created At,Screen Name,tweets,Location,Number of Retweet,Number of Like
0,2023-05-18 10:28:40+00:00,Ilyas55120860,RT @alfajri221810: @ListyoSigitP kayaknya jarg...,,1,0
1,2023-05-18 10:28:21+00:00,heffheven,"RT @hoobaei: @tanyarlfes bisa dua duanya, terg...",,3,0
2,2023-05-18 10:21:44+00:00,byeorida,"@tanyarlfes Bisa dua-duanya, tergantung kontek...",,0,0
3,2023-05-18 10:20:54+00:00,kamaloeby,@CNNIndonesia pengganti satgasus sambo yg ceme...,,0,0
4,2023-05-18 10:14:04+00:00,sugarcandyblue,@PortgasD_Jay sambo egx jelas\nak cuman berani...,"Harta, Tahta, Dimension Walker",0,0
5,2023-05-18 10:11:11+00:00,alin_raihani,@KangManto123 Lihat aja kasus sambo..teddy min...,,0,0
6,2023-05-18 10:09:28+00:00,abimandaru,@KompasTV Kasusnya hrs dibuka @mohmahfudmd spy...,,0,0
7,2023-05-18 10:08:06+00:00,hoobaei,"@tanyarlfes bisa dua duanya, tergantung kontek...",,3,159
8,2023-05-18 10:07:16+00:00,alfajri221810,@ListyoSigitP kayaknya jargon Polri presisi cu...,"Borobudur, Indonesia",1,0
9,2023-05-18 09:57:01+00:00,AndiBoga06,@putra_adrin @Restty_cayah Sambo agak mengarah...,"Kota Medan, Sumatera Utara",0,1
10,2023-05-18 09:56:37+00:00,Lindiwe_Sambo,RT @claztik17: Woman In Yellow ðŸŸ¡\nx Baba Tjek ...,,64,0
11,2023-05-18 09:51:42+00:00,asykadi,RT @BelengBeleng687: Novum kasus KM 50 gamblan...,"Padang Panjang, Indonesia",171,0
12,2023-05-18 09:48:34+00:00,neverlandalien,@hzgld ucing aing ge asalna ngaranna ferdy jen...,,0,0
13,2023-05-18 09:37:22+00:00,alfajri221810,@ListyoSigitP Polri presisi cuma basa basi..\n...,"Borobudur, Indonesia",0,0
14,2023-05-18 09:36:31+00:00,putra_adrin,@AndiBoga06 @Restty_cayah SAMBO JUGA SANTUN......,"Jakarta Selatan, DKI Jakarta",0,0
15,2023-05-18 09:29:02+00:00,Lindiwe_Sambo,RT @siphosenkosi_n: Izolo uthe esaye toilet ng...,,19,0
16,2023-05-18 09:26:26+00:00,MSikakulya,@Mereal_sambo @Xarah_Sulayman Asalam aleikum w...,,0,0
17,2023-05-18 09:20:37+00:00,silumanTai,@sayap2_sambo @mailbukanmael @volleyballidn na...,"á¨†á¨€á¨”á¨‘ -5.1290137, 119.4369486",0,0
18,2023-05-18 09:19:29+00:00,bagusal04043501,Sepertinya akan ada lagi lagu baru yg akan ril...,,0,0
19,2023-05-18 09:12:02+00:00,PrinceMokoena14,@sambo_njabulo Yeah ku tirhiwile,,0,0